interface CategoryWord {
  word: string;
  hint?: string;
}

interface Category {
  name: string;
  description: string;
  words: CategoryWord[];
}

export const CATEGORIES: Record<string, Category> = {
  animals: {
    name: 'Animals',
    description: 'Common animals you might know',
    words: [
      { word: 'dog' },
      { word: 'cat' },
      { word: 'mouse' },
      { word: 'lion' },
      { word: 'bear' },
      { word: 'tiger' },
      { word: 'wolf' },
      { word: 'fox' },
      { word: 'deer' },
      { word: 'duck' },
      { word: 'goose' },
      { word: 'swan' },
      { word: 'owl' },
      { word: 'hawk' },
      { word: 'eagle' },
      { word: 'crow' },
      { word: 'dove' },
      { word: 'robin' },
      { word: 'fish' },
      { word: 'shark' },
      { word: 'whale' },
      { word: 'seal' },
      { word: 'otter' },
      { word: 'rabbit' },
      { word: 'horse' },
      { word: 'cow' },
      { word: 'pig' },
      { word: 'sheep' },
      { word: 'goat' },
      { word: 'chicken' },
    ]
  },
  fruits: {
    name: 'Fruits',
    description: 'Delicious fruits from around the world',
    words: [
      { word: 'apple' },
      { word: 'banana' },
      { word: 'orange' },
      { word: 'mango' },
      { word: 'grape' },
      { word: 'lemon' },
      { word: 'lime' },
      { word: 'cherry' },
      { word: 'berry' },
      { word: 'peach' },
      { word: 'pear' },
      { word: 'plum' },
      { word: 'kiwi' },
      { word: 'melon' },
      { word: 'papaya' },
      { word: 'guava' },
      { word: 'fig' },
      { word: 'date' },
      { word: 'coconut' },
      { word: 'avocado' },
      { word: 'pineapple' },
      { word: 'strawberry' },
      { word: 'blueberry' },
      { word: 'raspberry' },
      { word: 'blackberry' },
      { word: 'cranberry' },
      { word: 'apricot' },
      { word: 'tangerine' },
      { word: 'grapefruit' },
      { word: 'pomegranate' },
    ]
  },
  colors: {
    name: 'Colors',
    description: 'Basic colors we see everyday',
    words: [
      { word: 'red' },
      { word: 'blue' },
      { word: 'green' },
      { word: 'yellow' },
      { word: 'white' },
      { word: 'black' },
      { word: 'brown' },
      { word: 'gray' },
      { word: 'pink' },
      { word: 'purple' },
      { word: 'orange' },
      { word: 'violet' },
      { word: 'indigo' },
      { word: 'cyan' },
      { word: 'magenta' },
      { word: 'silver' },
      { word: 'gold' },
      { word: 'bronze' },
      { word: 'maroon' },
      { word: 'navy' },
      { word: 'teal' },
      { word: 'olive' },
      { word: 'lime' },
      { word: 'aqua' },
      { word: 'coral' },
      { word: 'salmon' },
      { word: 'crimson' },
      { word: 'scarlet' },
      { word: 'azure' },
      { word: 'beige' },
    ]
  },
  foods: {
    name: 'Foods',
    description: 'Tasty foods and ingredients',
    words: [
      { word: 'bread' },
      { word: 'rice' },
      { word: 'pasta' },
      { word: 'pizza' },
      { word: 'burger' },
      { word: 'sandwich' },
      { word: 'salad' },
      { word: 'soup' },
      { word: 'stew' },
      { word: 'cake' },
      { word: 'cookie' },
      { word: 'pie' },
      { word: 'donut' },
      { word: 'muffin' },
      { word: 'bagel' },
      { word: 'waffle' },
      { word: 'pancake' },
      { word: 'eggs' },
      { word: 'bacon' },
      { word: 'cheese' },
      { word: 'butter' },
      { word: 'milk' },
      { word: 'yogurt' },
      { word: 'honey' },
      { word: 'jam' },
      { word: 'nuts' },
      { word: 'chips' },
      { word: 'popcorn' },
      { word: 'chocolate' },
      { word: 'candy' },
    ]
  },
  sports: {
    name: 'Sports',
    description: 'Popular sports and activities',
    words: [
      { word: 'soccer' },
      { word: 'football' },
      { word: 'basketball' },
      { word: 'baseball' },
      { word: 'tennis' },
      { word: 'golf' },
      { word: 'swimming' },
      { word: 'running' },
      { word: 'cycling' },
      { word: 'boxing' },
      { word: 'wrestling' },
      { word: 'hockey' },
      { word: 'cricket' },
      { word: 'rugby' },
      { word: 'volleyball' },
      { word: 'badminton' },
      { word: 'skiing' },
      { word: 'snowboarding' },
      { word: 'surfing' },
      { word: 'sailing' },
      { word: 'fishing' },
      { word: 'hunting' },
      { word: 'archery' },
      { word: 'fencing' },
      { word: 'martial' },
      { word: 'yoga' },
      { word: 'dancing' },
      { word: 'climbing' },
      { word: 'hiking' },
      { word: 'camping' },
    ]
  },
  nature: {
    name: 'Nature',
    description: 'Elements from the natural world',
    words: [
      { word: 'tree' },
      { word: 'flower' },
      { word: 'grass' },
      { word: 'leaf' },
      { word: 'branch' },
      { word: 'root' },
      { word: 'seed' },
      { word: 'forest' },
      { word: 'mountain' },
      { word: 'hill' },
      { word: 'valley' },
      { word: 'river' },
      { word: 'lake' },
      { word: 'ocean' },
      { word: 'beach' },
      { word: 'sand' },
      { word: 'rock' },
      { word: 'stone' },
      { word: 'cave' },
      { word: 'desert' },
      { word: 'island' },
      { word: 'cloud' },
      { word: 'rain' },
      { word: 'snow' },
      { word: 'wind' },
      { word: 'storm' },
      { word: 'thunder' },
      { word: 'lightning' },
      { word: 'rainbow' },
      { word: 'sunshine' },
    ]
  },
  countries: {
    name: 'Countries',
    description: 'Nations and countries around the world',
    words: [
      { word: 'usa' },
      { word: 'canada' },
      { word: 'mexico' },
      { word: 'brazil' },
      { word: 'argentina' },
      { word: 'chile' },
      { word: 'peru' },
      { word: 'colombia' },
      { word: 'venezuela' },
      { word: 'ecuador' },
      { word: 'bolivia' },
      { word: 'uruguay' },
      { word: 'paraguay' },
      { word: 'france' },
      { word: 'germany' },
      { word: 'italy' },
      { word: 'spain' },
      { word: 'portugal' },
      { word: 'england' },
      { word: 'scotland' },
      { word: 'ireland' },
      { word: 'wales' },
      { word: 'poland' },
      { word: 'russia' },
      { word: 'ukraine' },
      { word: 'norway' },
      { word: 'sweden' },
      { word: 'finland' },
      { word: 'denmark' },
      { word: 'iceland' },
      { word: 'austria' },
      { word: 'switzerland' },
      { word: 'netherlands' },
      { word: 'belgium' },
      { word: 'luxembourg' },
      { word: 'czech' },
      { word: 'slovakia' },
      { word: 'hungary' },
      { word: 'romania' },
      { word: 'bulgaria' },
      { word: 'greece' },
      { word: 'turkey' },
      { word: 'cyprus' },
      { word: 'malta' },
      { word: 'croatia' },
      { word: 'slovenia' },
      { word: 'serbia' },
      { word: 'bosnia' },
      { word: 'albania' },
      { word: 'macedonia' },
      { word: 'montenegro' },
      { word: 'estonia' },
      { word: 'latvia' },
      { word: 'lithuania' },
      { word: 'belarus' },
      { word: 'moldova' },
      { word: 'china' },
      { word: 'japan' },
      { word: 'korea' },
      { word: 'india' },
      { word: 'pakistan' },
      { word: 'bangladesh' },
      { word: 'sri' },
      { word: 'nepal' },
      { word: 'bhutan' },
      { word: 'maldives' },
      { word: 'thailand' },
      { word: 'vietnam' },
      { word: 'cambodia' },
      { word: 'laos' },
      { word: 'myanmar' },
      { word: 'malaysia' },
      { word: 'singapore' },
      { word: 'indonesia' },
      { word: 'philippines' },
      { word: 'brunei' },
      { word: 'australia' },
      { word: 'zealand' },
      { word: 'fiji' },
      { word: 'samoa' },
      { word: 'tonga' },
      { word: 'vanuatu' },
      { word: 'egypt' },
      { word: 'libya' },
      { word: 'tunisia' },
      { word: 'algeria' },
      { word: 'morocco' },
      { word: 'sudan' },
      { word: 'ethiopia' },
      { word: 'kenya' },
      { word: 'tanzania' },
      { word: 'uganda' },
      { word: 'rwanda' },
      { word: 'burundi' },
      { word: 'congo' },
      { word: 'cameroon' },
      { word: 'nigeria' },
      { word: 'ghana' },
      { word: 'ivory' },
      { word: 'senegal' },
      { word: 'mali' },
      { word: 'niger' },
      { word: 'chad' },
      { word: 'zambia' },
      { word: 'zimbabwe' },
      { word: 'botswana' },
      { word: 'namibia' },
      { word: 'angola' },
      { word: 'mozambique' },
      { word: 'madagascar' },
      { word: 'mauritius' },
    ]
  },
};

export const generateBlocksFromWords = (words: string[]): string[] => {
  // Combine all words and convert to uppercase
  const letters = words.join('').toUpperCase().split('');
  // Shuffle the letters
  return letters.sort(() => Math.random() - 0.5);
};

export const isWordPossible = (word: string, blocks: string[]): boolean => {
  const availableBlocks = [...blocks];
  const wordLetters = word.toUpperCase().split('');

  return wordLetters.every(letter => {
    const index = availableBlocks.indexOf(letter);
    if (index === -1) return false;
    availableBlocks.splice(index, 1);
    return true;
  });
};
